modLoader = "javafml"
loaderVersion = "[35,)"
license = "I don't know the license"
[[mods]]

modId = "aether"
version = "${file.jarVersion}"
displayName = "The Aether"
displayURL = "https://gildedgames.com/"
logoFile = "aether.png"
credits = "Gilded Games; Modding Legacy for the original Aether Legacy port"
authors = "Raptor4694, quek, bconlon"
description = '''
The Aether, a hostile paradise in the skies.
'''

[[dependencies.aether]]
    modId = "forge"
    mandatory = true
    versionRange = "[35,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether]]
    modId = "curios"
    mandatory = true
    versionRange = "[4,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.4]"
    ordering = "NONE"
    side = "BOTH"
