modLoader = "javafml"
loaderVersion = "[31,)"

[[mods]]

modId = "aether"
version = "1.15.2-v1.5.0"
displayName = "The Aether"
displayURL = "https://gildedgames.com/"
logoFile = "aether.png"
credits = "Gilded Games; also InsomniaKitten for providing the inventory texture."
authors = "Raptor4694, quek, bconlon"
description = '''
The Aether, a hostile paradise in the skies.
'''

[[dependencies.aether]]
    modId = "forge"
    mandatory = true
    versionRange = "[31,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.15.2]"
    ordering = "NONE"
    side = "BOTH"
