version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      _JAVA_OPTIONS: -Xmx3200m

      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "build.gradle" }}
            - v3-dependencies-

      - run:
          command: |
            while true; do
              sleep 5
              ps auxwwf
              echo "======"
            done
          background: true

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/repo/.gradle
          key: v3-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test
      - run: gradle build
      - store_artifacts:
              path: ~/repo/build/libs
