version: 2.1

parameters:
  artifact:
    type: string
    default: aether-{CIRCLE_BRANCH}.jar

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.282
    # machine:
    #   image: ubuntu-2004:202104-01

    environment:
      JVM_OPTS: -Xmx3200m
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v3-dependencies-{{ checksum "build.gradle" }}
      #       - v3-dependencies-

      # - run: gradle dependencies
      # - save_cache:
      #     paths:
      #       - ~/repo/.gradle
      #     key: v3-dependencies-{{ checksum "build.gradle" }}
      # - run: gradle test
      # - run: gradle build
      - run: mkdir -p ~/project/build/libs
      - run: echo "test" > ~/project/build/libs/<< pipeline.parameters.artifact >>
      - store_artifacts:
          path: ~/project/build/libs
      - persist_to_workspace:
          root: ~/project/build/libs
          paths: 
            - << pipeline.parameters.artifact >>

  deploy:
    docker:
      - image: cimg/base:2021.07
    steps:
      - attach_workspace:
          at: ~/project
      - run: git clone git@github.com:Gilded-Games/pterodactyl-server-images.git
      - run: ls -a
      - setup_remote_docker:
          version: 19.03.13
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build --build-arg ARTIFACT=<< pipeline.parameters.artifact >> -t gildedgames/aether-server:$CIRCLE_BRANCH .
      - run: docker push gildedgames/aether-server:$CIRCLE_BRANCH 

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context:
            - docker
          # filters:
          #   branches:
          #     only: 
          #       - "main"
          requires:
            - build