version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.282
    # machine:
    #   image: ubuntu-2004:202104-01
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v3-dependencies-{{ checksum "build.gradle" }}
      #       - v3-dependencies-

      # - run: gradle dependencies
      # - save_cache:
      #     paths:
      #       - ~/repo/.gradle
      #     key: v3-dependencies-{{ checksum "build.gradle" }}
      # - run: gradle test
      # - run: gradle build
      - run: mkdir -p ~/repo/build/libs
      - run: echo "test" > ~/repo/build/libs/test.jar
      - store_artifacts:
          path: ~/repo/build/libs
      - persist_to_workspace:
          root: ~/repo/build/
          paths: 
            - libs

  deploy:
    docker:
      - image: cimg/base:2021.07
    
    steps:
      - attach_workspace:
          at: ~/libs
      - run: cd libs && ls -a 
      - run: |
            echo "
            FROM openjdk:8-jre-slim
            RUN apt-get update -y \
            && apt-get install -y curl ca-certificates openssl git tar sqlite fontconfig tzdata iproute2 \
            && useradd -d /home/container -m container
            
            USER container
            ENV USER=container HOME=/home/container

            USER container
            ENV USER=container HOME=/home/container

            WORKDIR /home/container

            COPY ./libs/test.jar /mods/test.jar
            COPY ./entrypoint.sh /entrypoint.sh
            " > Dockerfile
      - run: cat Dockerfile
    

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          # filters:
          #   branches:
          #     only: 
          #       - "main"
          requires:
            - build