version: 2.1

jobs:
  build:
    # docker:
    #   - image: cimg/openjdk:8.0.282
    machine:
      image: ubuntu-2004:202104-01
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "build.gradle" }}
            - v3-dependencies-

      - run:
          command: |
            while true; do
              sleep 5
              ps auxwwf
              echo "======"
            done
          background: true

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/repo/.gradle
          key: v3-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test
      - run: gradle build
      - store_artifacts:
              path: ~/repo/build/libs
