version: 2.1

parameters:
  artifact-name:
    type: string
    default: aether

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.282
    # machine:
    #   image: ubuntu-2004:202104-01

    environment:
      JVM_OPTS: -Xmx3200m
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v3-dependencies-{{ checksum "build.gradle" }}
      #       - v3-dependencies-

      # - run: gradle dependencies
      # - save_cache:
      #     paths:
      #       - ~/repo/.gradle
      #     key: v3-dependencies-{{ checksum "build.gradle" }}
      # - run: gradle test
      # - run: gradle build
      - run: mkdir -p ~/project/build/libs
      - run: echo "test" > ~/project/build/libs/<< pipeline.parameters.artifact-name >>-${CIRCLE_BRANCH}.jar
      - store_artifacts:
          path: ~/project/build/libs
      - persist_to_workspace:
          root: ~/project/build/libs
          paths: 
            - << pipeline.parameters.artifact-name >>-*.jar

  deploy:
    docker:
      - image: cimg/base:2021.07
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
            SSH_CONFIG_DIR=/home/circleci/.ssh
            echo "Using SSH Config Dir '$SSH_CONFIG_DIR'"
            git --version 

            mkdir -p "$SSH_CONFIG_DIR"
            chmod 0700 "$SSH_CONFIG_DIR"
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> "$SSH_CONFIG_DIR/known_hosts"
            chmod 0600 "$SSH_CONFIG_DIR/known_hosts"
      - run: git clone git@github.com:Gilded-Games/pterodactyl-server-images.git ./pterodactyl-server-images
      - run: mv ./<< pipeline.parameters.artifact-name >>-${CIRCLE_BRANCH}.jar ./pterodactyl-server-images
      - setup_remote_docker:
          version: 19.03.13
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build --build-arg BUILD_ARTIFACT=<< pipeline.parameters.artifact-name >>-${CIRCLE_BRANCH}.jar -t gildedgames/aether-server:$CIRCLE_BRANCH pterodactyl-server-images
      - run: docker push gildedgames/aether-server:$CIRCLE_BRANCH 

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context:
            - docker
          # filters:
          #   branches:
          #     only: 
          #       - "main"
          requires:
            - build